[package]
name = "grid"
version = "0.1.0"
description = "A speedy concurrent hashmap"
readme = "README.md"
repository = "https://github.com/currysoup/grid"
license = "MIT"
authors = ["Sam Cutler <sam92cutler@gmail.com>"]

[dependencies]
crossbeam = "0.2.8"
